Drop database Restaurante
Create database Restaurante

use Restaurante

drop table if exists Proveedores;
Create table Proveedores(
id_proveedor int not null auto_increment primary key,
Nombre varchar (255),
Telefono varchar (255),
Correo varchar(255)
);

drop table if exists Ingredientes;
Create table Ingredientes (
id_ingrediente int not null auto_increment,
Frutas_verduras varchar (255),
Supermercado varchar (255),
Carnes Varchar (255),
id_proveedor int,
primary key (id_ingrediente),
Foreign key (id_proveedor) references Proveedores(id_proveedor)
);

drop table if exists Platillo;
Create table Platillo (
id_platillo int not null auto_increment primary key, 
Nombre varchar (255),
Precio_venta int,
id_ingrediente int,
Foreign key (id_ingrediente) references Ingredientes(id_ingrediente)
);

drop table if exists Ventas;
Create table Ventas(
id_venta int not null primary key,
Mes Varchar(255),
Cantidad_vendida Varchar(255),
Platillo varchar(255),
id_platillo int,
Foreign key(id_platillo) references Platillo (id_platillo));



Insert into Restaurante.Ingredientes(id_ingrediente,Frutas_verduras,Supermercado,Carnes)
Values
(null,"AGUACATE MEDIO VERDE"," "," "),
(null,null,'AJO',null),
( null,null,'AJONJOLI',null),
(null,null,'ALBAHACA',null),
(null,null,'AVENA',null),
(null,'APIO',null,null),
(null,'BETABEL',null,null),
(null,null,'BOLSAS DE BASURA',null),
(null,null,'BOLSAS DE CAMISETA',null),
(null,null,'BOLSAS DE PAPEL PARA PAN',null),
(null,null,'BOLSAS DE PAPEL PARA SERVICIO',null),
(null,'BROCOLI',null,null),
(null,null,'CACAHUATE BLANCO',null),
(null,'CALABAZA',null,null),
(null,'CAMOTE AMARILLO',null,null),
(null,'CEBOLLA BLANCA EXTRA',null,null),
(null,'CEBOLLA MORADA EXTRA',null,null),
(null,'CEBOLLIN',null,null),
(null,'CHAMPIÑONES',null,null),
(null,'CHAYOTE',null,null),
(null,null,'CHIA',null),
(null,null,null,'CHICHARRON CASCARA'),
(null,'CHILE HABANERO',null,null),
(null,'CHILE MORRON COLORES',null,null),
(null,'CHILE POBLANO',null,null),
(null,'CHILE VERDE',null,null),
(null,'CILANTRO',null,null),
(null,'COL MORADO',null,null),
(null,null,'CUCHARAS DESECHABLES',null),
(null,'ELOTES EN MAZORCA',null,null),
(null,'ELOTE EN GRANO',null,null),
(null,'EPAZOTE',null,null),
(null,'ESPINACA',null,null),
(null,'FRESAS',null,null),
(null,'FRIJOL',null,null),
(null,'GENGIBRE',null,null),
(null,'GUINEO',null,null),
(null,'SEMILLA DE GIRASOL',null,null),
(null,'LIMON',null,null),
(null,null,'MASA',null),
(null,'MELON',null,null),
(null,'MORAS',null,null),
(null,'NARANJAS',null,null),
(null,'NOPAL',null,null),
(null,'OREGANO',null,null),
(null,'PAPA CAMBRAY',null,null),
(null,'PAPA GRANDE',null,null),
(null,'PAPAYA',null,null),
(null,'PEPINO',null,null),
(null,'PEREJIL',null,null),
(null,'PIÑA',null,null),
(null,null,'PLASTICO FILM',null),
(null,'PLATANO',null,null),
(null,'PORO',null,null),
(null,'QUESO CHIAPAS',null,null),
(null,'RABANO',null,null),
(null,'SANDIA',null,null),
(null,null,'TASCALATE',null),
(null,null,'TENEDORES DESECHABLES',null),
(null,'TOMATE ROJO CHICO',null,null),
(null,'TOMATE ROJO MEDIANO',null,null),
(null,'TOMATE VERDE',null,null),
(null,'TOMILLO',null,null),
(null,'ZANAHORIA',null,null),
(null,null,'MANTECA',null),
(null,'SEMILLA DE CALABAZA',null,null),
(null,'PIMIENTA GORDA',null,null),
(null,'CREMA PARA MESEROS',null,null),
(null,null,null,'camaron fresco'),
(null,null,null,'camaron seco'),
(null,'canela',null,null),
(null,'chile ancho',null,null),
(null,'chile guajillo',null,null),
(null,'Chile pasilla',null,null),
(null,null,'chocolate',null),
(null,null,null,'filete pescado'),
(null,'jamaica',null,null),
(null,'SEMILLA DE GIRASOL',null,null),
(null,'AVENA',null,null),
(null,null,null,'Pollo'),
(null,null,null,'Res');

Insert into platillo(nombre)
Values 
("1/2 ARROZ DE OLLITA"),
("ARRACHERA AL GRILL"),
("ARROZ CALDOSO"),
("ARROZ DE OLLITA"),
("CALDO DE CAMARON"),
("CALDO DE PATA Y PANZA"),
("CALDO TLALPEÑO"),
("CAMARONES AL MOJO DE AJO"),
("CAMARONES EMPANIZADOS"),
("CAMARONES TEMPURA"),
("CAZUELA COLETA"),
("CAZUELA LUNA"),
("CAZUELA SOL"),
("CECINA"),
("CHAROLA"),
("CHAROLA GRANDE"),
("CHEESECAKE"),
("CLUB SANDWICH"),
("COCHITO HORNEADO A LA CAZUELA"),
("COCTEL DE CAMARON"),
("CONSOME CON PZ"),
("CONSOME DE POLLO"),
("CONSOME DE POLLO"),
("CONSOME PEKE"),
("COSTILLAS FRITAS"),
("CREMA DEL DIA"),
("DE CARNITA"),
("EMPANADA GIGANTE 1 INGRE."),
("EMPANADA GIGANTE 2 INGRE."),
("EMPANADA GIGANTE 3 INGRE."),
("EMPANADA GIGANTE TODOS INGREDIENTES"),
("ENSALADA DE CAMARON"),
("ENSALADA LUNA"),
("ENSALADA SOL"),
("ENSALADA UNICA"),
("ESPAGUETI ALFREDO"),
("ESPAGUETI FRITO"),
("ESPAGUETI POLLO C/ESPINACA"),
("EVENTO NIÑOS"),
("FAJITAS DE POLLO"),
("FAJITAS DE POLLO GRATINADO"),
("FAJITAS DE RES"),
("FAJITAS DE RES GRATINADO"),
("FAJITAS MAR Y TIERRA"),
("FAJITAS MAR Y TIERRA GRATINADO"),
("FAJITAS VEGETARIANAS"),
("FILETE A LA PLANCHA"),
("FILETE AL CHIPOTLE"),
("FILETE AL CILANTRO"),
("FILETE DE PESCADO  A LA PARMESANA"),
("FLAN NAPOLITANO"),
("HAMBURGUESA BBQ"),
("HAMBURGUESA BBQ DOBLE"),
("HAMBURGUESA CLASICA"),
("HAMBURGUESA DOBLE"),
("HELADO"),
("HOT CAKE DULCE DE LECHE"),
("HUEVOS CON JAMON P/PEQUES"),
("MENU DE 75"),
("MILANESA DE POLLO"),
("MILANESA RELLENA"),
("MINI TARTAS"),
("MOJARRA"),
("PAN DE ELOTE"),
("PAQUETE"),
("PAQUETE BUFET"),
("PAQUETE+40"),
("PARA PEQUE ESPAGUETI A LA CREMA"),
("PARA PEQUES HOTCAKES"),
("PARA PEQUES MINI PIZZA"),
("PARA PEQUES QUESADILLAS"),
("PARRILLADA"),
("PASTEL DE ZANAHORIA"),
("PAY"),
("PECHUGA A LA PLANCHA"),
("PECHUGA HAWAIANA"),
("PECHUGA MESTIZA"),
("PECHUGA RELLENA"),
("PLATO DUO"),
("POLLO EN MOLE"),
("POLLO ENTOMATADO"),
("POSTRE"),
("POZOLE ROJO ESTILO JALISCO"),
("PROMO 35"),
("PROMO PARR-SOP-JARRA MICH"),
("PUNTAS A LA MEXICANA"),
("QUESADILLA  GIGANTE 3 INGRE."),
("QUESADILLA GIGANTE 1 INGRE."),
("QUESADILLA GIGANTE 2 INGRE."),
("QUESADILLA GIGANTE TODOS INGREDIENTES"),
("QUESADILLAS ESPECIALES"),
("REFIL AGUA"),
("SALMON CAPULLO"),
("SOL Y LUNA"),
("SOLECITO COLETO"),
("SOLECITO SOÑADOR"),
("SOLECITO VIAJERO"),
("SOPA DE HONGOS"),
("SOPA DE MARISCO"),
("SOPA DE VERDURAS"),
("SOPA POBLANA"),
("TACO DE BISTEC"),
("TACO PASTOR"),
("TACOS DE ARRAHERA Y HONGOS"),
("TACOS DORADOS"),
("TACOS DORADOS VEGETARIANOS"),
("TACOS ESTILO BAJA"),
("TACOS ESTILO BAJA +20 CAMARON"),
("TACOS ESTILO BAJA DE HARINA"),
("TACOS ESTILO BAJA GRATINADO"),
("TAMPIQUEÑA DE POLLO"),
("TAMPIQUEÑA DE RES"),
("TORTAS"),
("TOSTADA DE CAMARON"),
("TOSTADAS PZ"),
("VEGGIE BURGUER"),
("COPA CLERICOT"),
("TEQUILA"),
("CAFE AMERICANO"),
("CAFE DE OLLA CON CANELA"),
("CAFE LECHERO"),
("CAFE REFILL"),
("CAFÉ CON LECHE"),
("CAFÉ CON LECHE"),
("CAPUCHINO C/BAYLEYS"),
("CAPUCHINO CLASICO"),
("CAPUCHINO DE SABOR"),
("CHAMPURRADO"),
("CHOCOLATE"),
("DESECHABLE"),
("DESHECHABLE BEBIDAS"),
("EXPRESSO"),
("EXTRA DE LECHE"),
("TES NATURALES"),
("VASO DE LECHE CHICO"),
("AGUA DE SABOR"),
("AGUA EMBOTELLADA"),
("AMBAR"),
("AZTECA DE ORO"),
("BOHEMIA"),
("BUCHANANS MASTER"),
("CABALLITO DON JULIO REPOSADO"),
("CABALLITO TEQUILA"),
("CERVEZA ULTRA"),
("CHELADA"),
("CHOCOMILK"),
("CLAMATO PREPARADO"),
("COCA"),
("COCTEL P/PAPA"),
("COPA DE VINO BLANCO"),
("COPA DE VINO TINTO"),
("CUERVO REPOSADO"),
("DON JULIO 70"),
("DON JULIO REPOSADO"),
("ETIQUETA NEGRA"),
("ETIQUETA ROJA"),
("HEINEKEN"),
("HORCHATA DE ARROZ"),
("HORCHATA DE TASCALATE"),
("INDIO"),
("JARRA DE AGUA"),
("JARRA DE AGUA MINERAL"),
("JARRA DE CLERICOT"),
("JARRA DE HORCHATA"),
("JARRA DE MICHELADA"),
("JARRA LIMON, CHIA Y PIÑA"),
("JARRA MINERAL"),
("LAGER"),
("LAS MORAS"),
("LICUADOS"),
("LIMON, CHIA Y PIÑA"),
("LIMONADA"),
("LIMONADA MINERAL"),
("MALTEADA CHOCOLATE"),
("MALTEADA DE VAINILLA"),
("MALTEADA FRESA"),
("MALTEADA OREO"),
("MICHELADA"),
("MUNDET"),
("NARANJADA"),
("NARANJADA MINERAL"),
("PEÑAFIEL NARANJA"),
("PEÑAFIEL SANGRIA"),
("PEÑAFIEL SQUER"),
("TECATE LIGH"),
("TORRES 10"),
("VASO"),
("CARAJILLO"),
("CLERICOT JARRA"),
("COPA DE VINO"),
("MARGARITA CON POSH"),
("MOJITO COLETO"),
("MOJITO CUBANO"),
("PIÑA COLADA"),
("SANGRIA PREPARADA"),
("CHILAQUILES CLASICOS"),
("CHILAQUILES CON ARRACHERA"),
("CHILAQUILES MIXTO DE POLLO"),
("CHILAQUILES MIXTO DE RES"),
("CON HUEVO"),
("DEL MAR"),
("DESAYUNO CLASICO"),
("DESAYUNO CLASICO"),
("DESAYUNO DEL JEFE"),
("DESAYUNO DOMI"),
("DESAYUNO LA DOÑA"),
("DESAYUNO MEXICANO"),
("DESAYUNO MEXICANO"),
("DESAYUNO MULATO"),
("DESAYUNO MULATO"),
("DESAYUNO ROSY"),
("ENCHILADAS DE MOLE"),
("ENCHILADAS ROJAS VEGETARIANAS"),
("ENCHILADAS SUIZAS"),
("ENCHILADAS VERACRUZANAS"),
("HOT CAKE ESPECIAL"),
("HOT CAKES"),
("HOTCAKES P/PEQUES"),
("HOTCAKES TRES LECHES"),
("HUEVOS AL ALBAÑIL"),
("HUEVOS CON CHORIZO"),
("HUEVOS CON JAMON"),
("HUEVOS CON MACHACA"),
("HUEVOS CON TOCINO"),
("HUEVOS DIVORCIADOS"),
("HUEVOS MIGAS"),
("HUEVOS MOTULEÑOS"),
("HUEVOS NATURALES"),
("HUEVOS ROTOS"),
("MOLOTES"),
("MUFFIN"),
("OMELET DE CLARAS"),
("OMELETTE DE CLARAS"),
("OMELETTE DE VERDURA"),
("OMELETTES DE CHAMPIÑONES"),
("OMELETTES DE ESPINACA"),
("OMELETTES DE HUITLACOCHE"),
("OMELETTES DE LA CASA"),
("OMELETTES EL CONSENTIDO"),
("OMELETTES LIGERO"),
("ORDEN DE PAN DULCE (5PZ)"),
("ORDEN DE PAN TOSTADO CON MERMELADA DE LA CASA"),
("PAN DULCE"),
("PAN ESTILO FRANCES"),
("PAN FRANCES"),
("PANQUE DE LIMON"),
("PAQ. EVENTO"),
("PAQUETE"),
("PAQUETE DE 35"),
("PAQUETE DE 40"),
("PAQUETE DE 45"),
("PAQUETE DE DESAYUNO"),
("PLATON DE FRUTA"),
("QUESADILLAS"),
("RANCHEROS"),
("ROSCA NAVIDEÑA"),
("SOPA DE GATO"),
("SOPA DE GATO"),
("SOPA DE GATO CON CHORIZO"),
("TAZON FRUTAL"),
("TORTILLA ESPECIAL"),
("TORTILLA MESTIZA"),
("TORTILLA MEXICANA"),
("TORTILLA PAISA"),
("WAFFLES PASION"),
("YOGURT CON FRUTA Y GRANOLA"),
("DESHECHABLE ALIMENTOS"),
("DESHECHABLE BEBIDAS"),
("RECIPIENTE P/LL"),
("CHAMPIÑON"),
("CHISTORRA FRITA"),
("EXTRA  DIEZ PESOS"),
("EXTRA CINCO PESOS"),
("EXTRA LECHERA"),
("EXTRAUNPESO"),
("GUACAMOLE"),
("ORDEN DE ARROZ"),
("ORDEN DE FRIJOLES"),
("ORDEN DE PAPAS FRITAS"),
("ORDEN DE PLATANOS FRITOS"),
("ORDEN DE VERDURAS"),
("PAPAS AL AJILLO"),
("PIÑA"),
("QUESO FUNDIDO CON CHORIZO"),
("TOCINO"),
("JARRA DE JUGO DE NARANJA"),
("JARRA DE JUGO RELAJANTE"),
("JUGO COMBINADO"),
("JUGO COMBO"),
("JUGO DE NARANJA"),
("JUGO DE ZANAHORIA"),
("JUGO RELAJANTE"),
("JUGO TROPICAL"),
("JUGO VERDE"),
("ARROZ-POZOLE"),
("CONSOME-ALBONDIGAS"),
("CONSOME-FILETE"),
("CONSOME-POLLO"),
("CONSOME-RES"),
("CREMA-ALBONDIGAS"),
("CREMA-FILETE"),
("CREMA-POLLO"),
("ENSALADA- ALBONDIGAS"),
("ENSALADA-FILETE"),
("ENSALADA-POLLO"),
("FILETE-CREMA"),
("FILETE-SOPA"),
("POLLO"),
("POLLO EN SALSA -SOPA"),
("POLLO EN SALSA-CONSOME"),
("POLLO EN SALSA-CREMA"),
("REFILL AGUA"),
("REFILL AGUA"),
("REFILLAGUA"),
("SOPA-FILETE"),
("SOPA-FLAUTA"),
("PAQUETE"),
("BEBIDA PERSONAL"),
("COMIDA PERSONAL"),
("DESAYUNO PERSONAL"),
("EVENTO"),
("PROMO JUEVES TAQUERO"),
("PROMO MARTES HAMBURGUESA+BEBIDA"),
("PROMO MIÉRCOLES COSTILLA+TAMPI"),
("PROMO TLALPEÑO (LUNES)"),
("PROMO VIERNES CERVEZAS");


Insert into Restaurante.Proveedores(id_proveedor,Nombre,Telefono,Correo)
Values 
(1,"Frutas_verduras",2222589301,"frutas_verduras@gmail.com"),
(2,"Supermercado",2221472940,"supermercado@gmail.com"),
(3,"Carnes",2220847593,"correo@gmail.com"); 


Insert into restaurante.Ventas(id_venta,Mes,Platillo,Cantidad_vendida)
values 
(	1	,"	enero	",	0	,"	1/2 ARROZ DE OLLITA	"),
(	2	,"	enero	",	0	,"	1/2 TLAPEÑO	"),
(	3	,"	enero	",	48	,"	ARRACHERA AL GRILL	"),
(	4	,"	enero	",	0	,"	ARROZ CALDOSO	"),
(	5	,"	enero	",	38	,"	ARROZ DE OLLITA	"),
(	6	,"	enero	",	14	,"	CALDO DE CAMARON	"),
(	7	,"	enero	",	105	,"	CALDO DE PATA Y PANZA	"),
(	8	,"	enero	",	124	,"	CALDO TLALPEÑO	"),
(	9	,"	enero	",	35	,"	CAMARONES AL MOJO DE AJO	"),
(	10	,"	enero	",	53	,"	CAMARONES EMPANIZADOS	"),
(	11	,"	enero	",	16	,"	CAMARONES TEMPURA	"),
(	12	,"	enero	",	0	,"	CAZUELA COLETA	"),
(	13	,"	enero	",	0	,"	CAZUELA LUNA	"),
(	14	,"	enero	",	0	,"	CAZUELA SOL	"),
(	15	,"	enero	",	0	,"	CECINA	"),
(	16	,"	enero	",	0	,"	CHAROLA	"),
(	17	,"	enero	",	0	,"	CHAROLA GRANDE	"),
(	18	,"	enero	",	86	,"	CHEESECAKE	"),
(	19	,"	enero	",	32	,"	CLUB SANDWICH	"),
(	20	,"	enero	",	0	,"	COCHITO HORNEADO A LA CAZUELA	"),
(	21	,"	enero	",	20	,"	COCTEL DE CAMARON	"),
(	22	,"	enero	",	0	,"	CONSOME CON PZ	"),
(	23	,"	enero	",	44	,"	CONSOME DE POLLO	"),
(	24	,"	enero	",	11	,"	CONSOME DE POLLO	"),
(	25	,"	enero	",	3	,"	CONSOME PEKE	"),
(	26	,"	enero	",	64	,"	COSTILLAS FRITAS	"),
(	27	,"	enero	",	5	,"	CREMA DEL DIA	"),
(	28	,"	enero	",	0	,"	DE CARNITA	"),
(	29	,"	enero	",	31	,"	EMPANADA GIGANTE 1 INGRE.	"),
(	30	,"	enero	",	6	,"	EMPANADA GIGANTE 2 INGRE.	"),
(	31	,"	enero	",	0	,"	EMPANADA GIGANTE 3 INGRE.	"),
(	32	,"	enero	",	1	,"	EMPANADA GIGANTE TODOS INGREDIENTES	"),
(	33	,"	enero	",	0	,"	ENSALADA DE CAMARON	"),
(	34	,"	enero	",	1	,"	ENSALADA LUNA	"),
(	35	,"	enero	",	0	,"	ENSALADA SOL	"),
(	36	,"	enero	",	16	,"	ENSALADA UNICA	"),
(	37	,"	enero	",	59	,"	ESPAGUETI ALFREDO	"),
(	38	,"	enero	",	0	,"	ESPAGUETI FRITO	"),
(	39	,"	enero	",	31	,"	ESPAGUETI POLLO C/ESPINACA	"),
(	40	,"	enero	",	0	,"	EVENTO NIÑOS	"),
(	41	,"	enero	",	14	,"	FAJITAS DE POLLO	"),
(	42	,"	enero	",	10	,"	FAJITAS DE POLLO GRATINADO	"),
(	43	,"	enero	",	62	,"	FAJITAS DE RES	"),
(	44	,"	enero	",	12	,"	FAJITAS DE RES GRATINADO	"),
(	45	,"	enero	",	88	,"	FAJITAS MAR Y TIERRA	"),
(	46	,"	enero	",	83	,"	FAJITAS MAR Y TIERRA GRATINADO	"),
(	47	,"	enero	",	0	,"	FAJITAS VEGETARIANAS	"),
(	48	,"	enero	",	18	,"	FILETE A LA PLANCHA	"),
(	49	,"	enero	",	0	,"	FILETE AL CHIPOTLE	"),
(	50	,"	enero	",	12	,"	FILETE AL CILANTRO	"),
(	51	,"	enero	",	33	,"	FILETE DE PESCADO  A LA PARMESANA	"),
(	52	,"	enero	",	16	,"	FLAN NAPOLITANO	"),
(	53	,"	enero	",	0	,"	HAMBURGUESA BBQ	"),
(	54	,"	enero	",	0	,"	HAMBURGUESA BBQ DOBLE	"),
(	55	,"	enero	",	70	,"	HAMBURGUESA CLASICA	"),
(	56	,"	enero	",	17	,"	HAMBURGUESA DOBLE	"),
(	57	,"	enero	",	2	,"	HELADO	"),
(	58	,"	enero	",	0	,"	HOT CAKE DULCE DE LECHE	"),
(	59	,"	enero	",	6	,"	HUEVOS CON JAMON P/PEQUES	"),
(	60	,"	enero	",	0	,"	MENU DE 75	"),
(	61	,"	enero	",	123	,"	MILANESA DE POLLO	"),
(	62	,"	enero	",	75	,"	MILANESA RELLENA	"),
(	63	,"	enero	",	0	,"	MINI TARTAS	"),
(	64	,"	enero	",	0	,"	MOJARRA	"),
(	65	,"	enero	",	0	,"	PAN DE ELOTE	"),
(	66	,"	enero	",	0	,"	PAQUETE	"),
(	67	,"	enero	",	0	,"	PAQUETE BUFET	"),
(	68	,"	enero	",	0	,"	PAQUETE+40	"),
(	69	,"	enero	",	3	,"	PARA PEQUE ESPAGUETI A LA CREMA	"),
(	70	,"	enero	",	0	,"	PARA PEQUES HOTCAKES	"),
(	71	,"	enero	",	67	,"	PARA PEQUES MINI PIZZA	"),
(	72	,"	enero	",	21	,"	PARA PEQUES QUESADILLAS	"),
(	73	,"	enero	",	176	,"	PARRILLADA	"),
(	74	,"	enero	",	7	,"	PASTEL DE ZANAHORIA	"),
(	75	,"	enero	",	39	,"	PAY	"),
(	76	,"	enero	",	49	,"	PECHUGA A LA PLANCHA	"),
(	77	,"	enero	",	115	,"	PECHUGA HAWAIANA	"),
(	78	,"	enero	",	56	,"	PECHUGA MESTIZA	"),
(	79	,"	enero	",	59	,"	PECHUGA RELLENA	"),
(	80	,"	enero	",	0	,"	PLATO DUO	"),
(	81	,"	enero	",	0	,"	POLLO EN MOLE	"),
(	82	,"	enero	",	0	,"	POLLO ENTOMATADO	"),
(	83	,"	enero	",	0	,"	POSTRE	"),
(	84	,"	enero	",	0	,"	POZOLE ROJO ESTILO JALISCO	"),
(	85	,"	enero	",	0	,"	PROMO 35	"),
(	86	,"	enero	",	0	,"	PROMO PARR-SOP-JARRA MICH	"),
(	87	,"	enero	",	31	,"	PUNTAS A LA MEXICANA	"),
(	88	,"	enero	",	0	,"	QUESADILLA  GIGANTE 3 INGRE.	"),
(	89	,"	enero	",	44	,"	QUESADILLA GIGANTE 1 INGRE.	"),
(	90	,"	enero	",	4	,"	QUESADILLA GIGANTE 2 INGRE.	"),
(	91	,"	enero	",	2	,"	QUESADILLA GIGANTE TODOS INGREDIENTES	"),
(	92	,"	enero	",	22	,"	QUESADILLAS ESPECIALES	"),
(	93	,"	enero	",	3	,"	REFIL AGUA	"),
(	94	,"	enero	",	0	,"	SALMON CAPULLO	"),
(	95	,"	enero	",	0	,"	SOL Y LUNA	"),
(	96	,"	enero	",	0	,"	SOLECITO COLETO	"),
(	97	,"	enero	",	0	,"	SOLECITO SOÑADOR	"),
(	98	,"	enero	",	0	,"	SOLECITO VIAJERO	"),
(	99	,"	enero	",	29	,"	SOPA DE HONGOS	"),
(	100	,"	enero	",	150	,"	SOPA DE MARISCO	"),
(	101	,"	enero	",	0	,"	SOPA DE VERDURAS	"),
(	102	,"	enero	",	0	,"	SOPA POBLANA	"),
(	103	,"	enero	",	163	,"	TACO DE BISTEC	"),
(	104	,"	enero	",	55	,"	TACO PASTOR	"),
(	105	,"	enero	",	0	,"	TACOS DE ARRAHERA Y HONGOS	"),
(	106	,"	enero	",	21	,"	TACOS DORADOS	"),
(	107	,"	enero	",	0	,"	TACOS DORADOS VEGETARIANOS	"),
(	108	,"	enero	",	8	,"	TACOS ESTILO BAJA	"),
(	109	,"	enero	",	5	,"	TACOS ESTILO BAJA +20 CAMARON	"),
(	110	,"	enero	",	0	,"	TACOS ESTILO BAJA DE HARINA	"),
(	111	,"	enero	",	0	,"	TACOS ESTILO BAJA GRATINADO	"),
(	112	,"	enero	",	15	,"	TAMPIQUEÑA DE POLLO	"),
(	113	,"	enero	",	111	,"	TAMPIQUEÑA DE RES	"),
(	114	,"	enero	",	0	,"	TORTAS	"),
(	115	,"	enero	",	15	,"	TOSTADA DE CAMARON	"),
(	116	,"	enero	",	19	,"	TOSTADAS PZ	"),
(	117	,"	enero	",	0	,"	VEGGIE BURGUER	"),
(	118	,"	enero	",	0	,"	COPA CLERICOT	"),
(	119	,"	enero	",	0	,"	TEQUILA	"),
(	120	,"	enero	",	441	,"	CAFE AMERICANO	"),
(	121	,"	enero	",	0	,"	CAFE DE OLLA CON CANELA	"),
(	122	,"	enero	",	44	,"	CAFE LECHERO	"),
(	123	,"	enero	",	210	,"	CAFE REFILL	"),
(	124	,"	enero	",	154	,"	CAFÉ CON LECHE	"),
(	125	,"	enero	",	16	,"	CAFÉ CON LECHE	"),
(	126	,"	enero	",	4	,"	CAPUCHINO C/BAYLEYS	"),
(	127	,"	enero	",	92	,"	CAPUCHINO CLASICO	"),
(	128	,"	enero	",	57	,"	CAPUCHINO DE SABOR	"),
(	129	,"	enero	",	0	,"	CHAMPURRADO	"),
(	130	,"	enero	",	148	,"	CHOCOLATE	"),
(	131	,"	enero	",	0	,"	DESECHABLE	"),
(	132	,"	enero	",	0	,"	DESHECHABLE BEBIDAS	"),
(	133	,"	enero	",	2	,"	EXPRESSO	"),
(	134	,"	enero	",	1	,"	EXTRA DE LECHE	"),
(	135	,"	enero	",	68	,"	TES NATURALES	"),
(	136	,"	enero	",	2	,"	VASO DE LECHE CHICO	"),
(	137	,"	enero	",	93	,"	AGUA DE SABOR	"),
(	138	,"	enero	",	29	,"	AGUA EMBOTELLADA	"),
(	139	,"	enero	",	42	,"	AMBAR	"),
(	140	,"	enero	",	0	,"	AZTECA DE ORO	"),
(	141	,"	enero	",	35	,"	BOHEMIA	"),
(	142	,"	enero	",	0	,"	BUCHANANS MASTER	"),
(	143	,"	enero	",	0	,"	CABALLITO DON JULIO REPOSADO	"),
(	144	,"	enero	",	0	,"	CABALLITO TEQUILA	"),
(	145	,"	enero	",	12	,"	CERVEZA ULTRA	"),
(	146	,"	enero	",	8	,"	CHELADA	"),
(	147	,"	enero	",	36	,"	CHOCOMILK	"),
(	148	,"	enero	",	1	,"	CLAMATO PREPARADO	"),
(	149	,"	enero	",	196	,"	COCA	"),
(	150	,"	enero	",	0	,"	COCTEL P/PAPA	"),
(	151	,"	enero	",	0	,"	COPA DE VINO BLANCO	"),
(	152	,"	enero	",	0	,"	COPA DE VINO TINTO	"),
(	153	,"	enero	",	0	,"	CUERVO REPOSADO	"),
(	154	,"	enero	",	0	,"	DON JULIO 70	"),
(	155	,"	enero	",	0	,"	DON JULIO REPOSADO	"),
(	156	,"	enero	",	0	,"	ETIQUETA NEGRA	"),
(	157	,"	enero	",	0	,"	ETIQUETA ROJA	"),
(	158	,"	enero	",	6	,"	HEINEKEN	"),
(	159	,"	enero	",	93	,"	HORCHATA DE ARROZ	"),
(	160	,"	enero	",	20	,"	HORCHATA DE TASCALATE	"),
(	161	,"	enero	",	10	,"	INDIO	"),
(	162	,"	enero	",	91	,"	JARRA DE AGUA	"),
(	163	,"	enero	",	5	,"	JARRA DE AGUA MINERAL	"),
(	164	,"	enero	",	0	,"	JARRA DE CLERICOT	"),
(	165	,"	enero	",	29	,"	JARRA DE HORCHATA	"),
(	166	,"	enero	",	23	,"	JARRA DE MICHELADA	"),
(	167	,"	enero	",	43	,"	JARRA LIMON, CHIA Y PIÑA	"),
(	168	,"	enero	",	1	,"	JARRA MINERAL	"),
(	169	,"	enero	",	53	,"	LAGER	"),
(	170	,"	enero	",	0	,"	LAS MORAS	"),
(	171	,"	enero	",	52	,"	LICUADOS	"),
(	172	,"	enero	",	85	,"	LIMON, CHIA Y PIÑA	"),
(	173	,"	enero	",	38	,"	LIMONADA	"),
(	174	,"	enero	",	24	,"	LIMONADA MINERAL	"),
(	175	,"	enero	",	3	,"	MALTEADA CHOCOLATE	"),
(	176	,"	enero	",	6	,"	MALTEADA DE VAINILLA	"),
(	177	,"	enero	",	20	,"	MALTEADA FRESA	"),
(	178	,"	enero	",	14	,"	MALTEADA OREO	"),
(	179	,"	enero	",	48	,"	MICHELADA	"),
(	180	,"	enero	",	7	,"	MUNDET	"),
(	181	,"	enero	",	98	,"	NARANJADA	"),
(	182	,"	enero	",	57	,"	NARANJADA MINERAL	"),
(	183	,"	enero	",	0	,"	PEÑAFIEL NARANJA	"),
(	184	,"	enero	",	1	,"	PEÑAFIEL SANGRIA	"),
(	185	,"	enero	",	0	,"	PEÑAFIEL SQUER	"),
(	186	,"	enero	",	4	,"	TECATE LIGH	"),
(	187	,"	enero	",	0	,"	TORRES 10	"),
(	188	,"	enero	",	0	,"	VASO	"),
(	189	,"	enero	",	0	,"	CARAJILLO	"),
(	190	,"	enero	",	0	,"	CLERICOT JARRA	"),
(	191	,"	enero	",	0	,"	COPA DE VINO	"),
(	192	,"	enero	",	0	,"	MARGARITA CON POSH	"),
(	193	,"	enero	",	0	,"	MOJITO COLETO	"),
(	194	,"	enero	",	0	,"	MOJITO CUBANO	"),
(	195	,"	enero	",	0	,"	PIÑA COLADA	"),
(	196	,"	enero	",	0	,"	SANGRIA PREPARADA	"),
(	197	,"	enero	",	131	,"	CHILAQUILES CLASICOS	"),
(	198	,"	enero	",	65	,"	CHILAQUILES CON ARRACHERA	"),
(	199	,"	enero	",	51	,"	CHILAQUILES MIXTO DE POLLO	"),
(	200	,"	enero	",	169	,"	CHILAQUILES MIXTO DE RES	"),
(	201	,"	enero	",	16	,"	CON HUEVO	"),
(	202	,"	enero	",	28	,"	DEL MAR	"),
(	203	,"	enero	",	40	,"	DESAYUNO CLASICO	"),
(	204	,"	enero	",	4	,"	DESAYUNO CLASICO	"),
(	205	,"	enero	",	0	,"	DESAYUNO DEL JEFE	"),
(	206	,"	enero	",	0	,"	DESAYUNO DOMI	"),
(	207	,"	enero	",	0	,"	DESAYUNO LA DOÑA	"),
(	208	,"	enero	",	26	,"	DESAYUNO MEXICANO	"),
(	209	,"	enero	",	3	,"	DESAYUNO MEXICANO	"),
(	210	,"	enero	",	10	,"	DESAYUNO MULATO	"),
(	211	,"	enero	",	0	,"	DESAYUNO MULATO	"),
(	212	,"	enero	",	0	,"	DESAYUNO ROSY	"),
(	213	,"	enero	",	43	,"	ENCHILADAS DE MOLE	"),
(	214	,"	enero	",	0	,"	ENCHILADAS ROJAS VEGETARIANAS	"),
(	215	,"	enero	",	41	,"	ENCHILADAS SUIZAS	"),
(	216	,"	enero	",	24	,"	ENCHILADAS VERACRUZANAS	"),
(	217	,"	enero	",	0	,"	HOT CAKE ESPECIAL	"),
(	218	,"	enero	",	37	,"	HOT CAKES	"),
(	219	,"	enero	",	0	,"	HOTCAKES P/PEQUES	"),
(	220	,"	enero	",	0	,"	HOTCAKES TRES LECHES	"),
(	221	,"	enero	",	134	,"	HUEVOS AL ALBAÑIL	"),
(	222	,"	enero	",	38	,"	HUEVOS CON CHORIZO	"),
(	223	,"	enero	",	14	,"	HUEVOS CON JAMON	"),
(	224	,"	enero	",	64	,"	HUEVOS CON MACHACA	"),
(	225	,"	enero	",	1	,"	HUEVOS CON TOCINO	"),
(	226	,"	enero	",	8	,"	HUEVOS DIVORCIADOS	"),
(	227	,"	enero	",	0	,"	HUEVOS MIGAS	"),
(	228	,"	enero	",	62	,"	HUEVOS MOTULEÑOS	"),
(	229	,"	enero	",	23	,"	HUEVOS NATURALES	"),
(	230	,"	enero	",	33	,"	HUEVOS ROTOS	"),
(	231	,"	enero	",	15	,"	MOLOTES	"),
(	232	,"	enero	",	0	,"	MUFFIN	"),
(	233	,"	enero	",	2	,"	OMELET DE CLARAS	"),
(	234	,"	enero	",	0	,"	OMELETTE DE CLARAS	"),
(	235	,"	enero	",	0	,"	OMELETTE DE VERDURA	"),
(	236	,"	enero	",	79	,"	OMELETTES DE CHAMPIÑONES	"),
(	237	,"	enero	",	33	,"	OMELETTES DE ESPINACA	"),
(	238	,"	enero	",	0	,"	OMELETTES DE HUITLACOCHE	"),
(	239	,"	enero	",	82	,"	OMELETTES DE LA CASA	"),
(	240	,"	enero	",	77	,"	OMELETTES EL CONSENTIDO	"),
(	241	,"	enero	",	0	,"	OMELETTES LIGERO	"),
(	242	,"	enero	",	11	,"	ORDEN DE PAN DULCE (5PZ)	"),
(	243	,"	enero	",	9	,"	ORDEN DE PAN TOSTADO CON MERMELADA DE LA CASA	"),
(	244	,"	enero	",	390	,"	PAN DULCE	"),
(	245	,"	enero	",	4	,"	PAN ESTILO FRANCES	"),
(	246	,"	enero	",	19	,"	PAN FRANCES	"),
(	247	,"	enero	",	0	,"	PANQUE DE LIMON	"),
(	248	,"	enero	",	0	,"	PAQ. EVENTO	"),
(	249	,"	enero	",	0	,"	PAQUETE	"),
(	250	,"	enero	",	241	,"	PAQUETE DE 35	"),
(	251	,"	enero	",	212	,"	PAQUETE DE 40	"),
(	252	,"	enero	",	0	,"	PAQUETE DE 45	"),
(	253	,"	enero	",	1	,"	PAQUETE DE DESAYUNO	"),
(	254	,"	enero	",	29	,"	PLATON DE FRUTA	"),
(	255	,"	enero	",	0	,"	QUESADILLAS	"),
(	256	,"	enero	",	11	,"	RANCHEROS	"),
(	257	,"	enero	",	0	,"	ROSCA NAVIDEÑA	"),
(	258	,"	enero	",	0	,"	SOPA DE GATO	"),
(	259	,"	enero	",	19	,"	SOPA DE GATO	"),
(	260	,"	enero	",	0	,"	SOPA DE GATO CON CHORIZO	"),
(	261	,"	enero	",	0	,"	TAZON FRUTAL	"),
(	262	,"	enero	",	0	,"	TORTILLA ESPECIAL	"),
(	263	,"	enero	",	0	,"	TORTILLA MESTIZA	"),
(	264	,"	enero	",	0	,"	TORTILLA MEXICANA	"),
(	265	,"	enero	",	0	,"	TORTILLA PAISA	"),
(	266	,"	enero	",	0	,"	WAFFLES PASION	"),
(	267	,"	enero	",	0	,"	YOGURT CON FRUTA Y GRANOLA	"),
(	268	,"	enero	",	58	,"	DESHECHABLE ALIMENTOS	"),
(	269	,"	enero	",	9	,"	DESHECHABLE BEBIDAS	"),
(	270	,"	enero	",	571	,"	RECIPIENTE P/LL	"),
(	271	,"	enero	",	1	,"	CHAMPIÑON	"),
(	272	,"	enero	",	0	,"	CHISTORRA FRITA	"),
(	273	,"	enero	",	166	,"	EXTRA  DIEZ PESOS	"),
(	274	,"	enero	",	86	,"	EXTRA CINCO PESOS	"),
(	275	,"	enero	",	0	,"	EXTRA LECHERA	"),
(	276	,"	enero	",	895	,"	EXTRAUNPESO	"),
(	277	,"	enero	",	18	,"	GUACAMOLE	"),
(	278	,"	enero	",	13	,"	ORDEN DE ARROZ	"),
(	279	,"	enero	",	21	,"	ORDEN DE FRIJOLES	"),
(	280	,"	enero	",	33	,"	ORDEN DE PAPAS FRITAS	"),
(	281	,"	enero	",	27	,"	ORDEN DE PLATANOS FRITOS	"),
(	282	,"	enero	",	1	,"	ORDEN DE VERDURAS	"),
(	283	,"	enero	",	12	,"	PAPAS AL AJILLO	"),
(	284	,"	enero	",	0	,"	PIÑA	"),
(	285	,"	enero	",	0	,"	QUESO FUNDIDO CON CHORIZO	"),
(	286	,"	enero	",	2	,"	TOCINO	"),
(	287	,"	enero	",	3	,"	JARRA DE JUGO DE NARANJA	"),
(	288	,"	enero	",	1	,"	JARRA DE JUGO RELAJANTE	"),
(	289	,"	enero	",	46	,"	JUGO COMBINADO	"),
(	290	,"	enero	",	5	,"	JUGO COMBO	"),
(	291	,"	enero	",	331	,"	JUGO DE NARANJA	"),
(	292	,"	enero	",	32	,"	JUGO DE ZANAHORIA	"),
(	293	,"	enero	",	62	,"	JUGO RELAJANTE	"),
(	294	,"	enero	",	0	,"	JUGO TROPICAL	"),
(	295	,"	enero	",	65	,"	JUGO VERDE	"),
(	296	,"	enero	",	16	,"	ARROZ-POZOLE	"),
(	297	,"	enero	",	6	,"	CONSOME-ALBONDIGAS	"),
(	298	,"	enero	",	0	,"	CONSOME-FILETE	"),
(	299	,"	enero	",	0	,"	CONSOME-POLLO	"),
(	300	,"	enero	",	4	,"	CONSOME-RES	"),
(	301	,"	enero	",	0	,"	CREMA-ALBONDIGAS	"),
(	302	,"	enero	",	0	,"	CREMA-FILETE	"),
(	303	,"	enero	",	7	,"	CREMA-POLLO	"),
(	304	,"	enero	",	0	,"	ENSALADA- ALBONDIGAS	"),
(	305	,"	enero	",	0	,"	ENSALADA-FILETE	"),
(	306	,"	enero	",	15	,"	ENSALADA-POLLO	"),
(	307	,"	enero	",	0	,"	FILETE-CREMA	"),
(	308	,"	enero	",	0	,"	FILETE-SOPA	"),
(	309	,"	enero	",	0	,"	POLLO	"),
(	310	,"	enero	",	0	,"	POLLO EN SALSA -SOPA	"),
(	311	,"	enero	",	0	,"	POLLO EN SALSA-CONSOME	"),
(	312	,"	enero	",	0	,"	POLLO EN SALSA-CREMA	"),
(	313	,"	enero	",	0	,"	REFILL AGUA	"),
(	314	,"	enero	",	0	,"	REFILL AGUA	"),
(	315	,"	enero	",	3	,"	REFILLAGUA	"),
(	316	,"	enero	",	6	,"	SOPA-FILETE	"),
(	317	,"	enero	",	4	,"	SOPA-FLAUTA	"),
(	318	,"	enero	",	0	,"	PAQUETE	"),
(	319	,"	enero	",	198	,"	BEBIDA PERSONAL	"),
(	320	,"	enero	",	103	,"	COMIDA PERSONAL	"),
(	321	,"	enero	",	105	,"	DESAYUNO PERSONAL	"),
(	322	,"	enero	",	20	,"	EVENTO	"),
(	323	,"	enero	",	0	,"	PROMO JUEVES TAQUERO	"),
(	324	,"	enero	",	0	,"	PROMO MARTES HAMBURGUESA+BEBIDA	"),
(	325	,"	enero	",	0	,"	PROMO MIÉRCOLES COSTILLA+TAMPI	"),
(	326	,"	enero	",	0	,"	PROMO TLALPEÑO (LUNES)	"),
(	327	,"	enero	",	0	,"	PROMO VIERNES CERVEZAS	");

UPDATE Restaurante.Ingredientes
SET Frutas_verduras = " " , Supermercado = " "
WHERE Carnes is not null;

